### ISSUE TITLE
Counter not increasing for MS Teams.

### ISSUE THREAD

**Issue by keyframe-one** [akump/MS-Teams-Always-Available#4]
We use a custom domain (https://teams.microsoft.com.mcas.ms/) for our MS Teams and the 'count' doesn't seem to increase. I am using the latest version of Edge with Win11. The MS Team is running as an 'APP'.

**Comment by akump** [comment]
Hi @Slikkit ,

I am not comfortable pushing changes like this directly to production. I did a prototype of what I think will work here: https://github.com/akump/MS-Teams-Always-Available/pull/5. Can you pull this code and run the src from chrome and test? If you're not familiar with loading unpacked extensions, then I can write you some notes if you'd like.

Andrew

**Comment by keyframe-one** [comment]
Hello @akump 

I'm not familiar with pulling code from Github or running source in Chrome. But, I am happy to test. 

Nick.

**Comment by akump** [comment]
Ok so in order to test follow these steps
1. Download the test code here: https://github.com/akump/MS-Teams-Always-Available/archive/refs/tags/mcas.zip
2. Unzip the folder
3. In chrome, go to the url: chrome://extensions/
4. Click Load Unpacked
5.
![2021-09-21 at 10 59 AM](https://user-images.githubusercontent.com/22382028/134195446-93d7e24b-e8cd-4b3c-8e89-5ee72c77ae8e.png)

6. Choose the directory you unzipped. This is the directory with files such as package.json, manifest.json gulpfile.js etc.
7. The extension should be installed and working. If not, let me know. At that point we would need to debug it, but I'm not sure that'll be possible.
8. The extension version for you should be 1.1.9

![2021-09-21 at 10 59 AM](https://user-images.githubusercontent.com/22382028/134195867-8460cccf-4c7d-45c1-8a30-5979fdbe51fe.png)

**Comment by StraggleCraft** [comment]
Appears to be working correctly
![keepalive1](https://user-images.githubusercontent.com/10663364/135705150-75118421-ce50-47db-a146-072572332662.png)

**Comment by keyframe-one** [comment]
Hello.

Sorry, I never got around to testing the new code. I've actually switched
employers so there is no more MS Teams.


*Nick Ralph*

Film | Photo | Edit | VFX | Producer

E // ***@***.***

P // +61 401 107 071 <+61%20401%20107%20071>

**Comment by akump** [comment]
@Slikkit @StraggleCraft Thanks for the feedback guys. Closing this out as resolved!
